In [87]:
from typing import Callable
from torchvision import models
import torch
input = torch.rand((2,3,224,224))
print(input)

tensor([[[[0.9431, 0.1140, 0.4176,  ..., 0.1386, 0.7548, 0.5712],
          [0.0877, 0.4247, 0.5589,  ..., 0.8116, 0.6912, 0.5512],
          [0.5777, 0.8973, 0.2589,  ..., 0.8527, 0.5948, 0.3601],
          ...,
          [0.9394, 0.5695, 0.7038,  ..., 0.0965, 0.7059, 0.4840],
          [0.4910, 0.0861, 0.3547,  ..., 0.5956, 0.0295, 0.1847],
          [0.0694, 0.6936, 0.1049,  ..., 0.0324, 0.0087, 0.6257]],

         [[0.5618, 0.7147, 0.9100,  ..., 0.3959, 0.2173, 0.7926],
          [0.1905, 0.0186, 0.7911,  ..., 0.3425, 0.8479, 0.0650],
          [0.1925, 0.2673, 0.2980,  ..., 0.5951, 0.6644, 0.2091],
          ...,
          [0.3178, 0.0025, 0.5104,  ..., 0.8617, 0.9164, 0.4366],
          [0.0404, 0.5511, 0.1685,  ..., 0.1696, 0.2602, 0.4719],
          [0.8863, 0.9895, 0.1654,  ..., 0.4979, 0.3122, 0.4018]],

         [[0.6137, 0.7177, 0.8440,  ..., 0.2369, 0.0539, 0.1532],
          [0.8892, 0.6606, 0.9929,  ..., 0.6740, 0.1686, 0.3901],
          [0.6641, 0.2304, 0.3987,  ..., 0

In [91]:
a = models.resnet18()
output_features = {layer: torch.empty(0) for layer in ['layer1','layer2','layer3','layer4', 'fc']}

def save_input_features(layer_id: str) -> Callable:
    def func(module, input, output):
        output_features[layer_id] = input
    return func

def process_intput_features(module, input):
    print(input[0].shape)
    print(len(input))
    print(input)
    return input[0]*2

model_layer_dict = dict([*a.named_modules()])
for layer_id in ['layer1','layer2','layer3','layer4']:
    layer = model_layer_dict[layer_id]
    layer.register_forward_hook(save_input_features(layer_id))

# model_layer_dict['fc'].register_forward_hook(save_intput_features('fc'))

In [93]:
# features.keys()
output_features['layer1']

(tensor([[[[0.2971, 0.2971, 0.6203,  ..., 1.2538, 0.4511, 1.0557],
           [0.3483, 0.7073, 1.3407,  ..., 1.1123, 1.4339, 1.4339],
           [0.9148, 0.6451, 1.2985,  ..., 2.0140, 2.0140, 1.4339],
           ...,
           [0.6411, 0.8014, 1.6078,  ..., 0.9235, 2.2598, 2.8920],
           [0.8541, 0.9542, 1.6586,  ..., 0.9186, 0.9856, 1.5364],
           [0.8285, 1.4148, 1.6586,  ..., 1.6803, 1.5788, 1.5364]],
 
          [[0.7493, 0.7420, 0.7283,  ..., 1.6258, 2.1694, 1.2786],
           [1.9083, 0.8327, 1.3374,  ..., 1.5484, 1.4262, 1.4262],
           [1.4483, 0.8327, 2.3026,  ..., 0.8237, 1.5628, 1.5628],
           ...,
           [0.9347, 1.0370, 1.3015,  ..., 1.4786, 1.4659, 1.4659],
           [0.9347, 1.0110, 1.0110,  ..., 2.3552, 2.3552, 1.4659],
           [1.0326, 1.8997, 1.6859,  ..., 2.3552, 2.3552, 1.0477]],
 
          [[0.0000, 0.0000, 0.1095,  ..., 0.0000, 0.0000, 0.8742],
           [0.3402, 0.7300, 1.1236,  ..., 2.8353, 1.1132, 0.8742],
           [0.0000, 0.48

In [92]:
output = a(input)
print(output.shape)

torch.Size([2, 1000])


In [61]:
model_layer_dict['fc'].register_forward_pre_hook(process_intput_features)

In [62]:
print(a(input))

torch.Size([1, 512])
1
(tensor([[0.8521, 0.8843, 0.8571, 0.8756, 0.8817, 0.6911, 0.8150, 0.7686, 0.8114,
         0.8035, 0.8053, 0.8745, 0.8230, 0.8477, 0.7836, 0.7642, 0.8472, 0.7740,
         0.7787, 0.8380, 0.8850, 0.8542, 0.8351, 0.8305, 0.7290, 0.7273, 0.7453,
         0.7277, 0.8082, 0.8099, 0.8460, 0.8099, 0.8420, 0.8395, 0.8212, 0.8286,
         0.7991, 0.7459, 0.7840, 0.8562, 0.8209, 0.8916, 0.7601, 0.8400, 0.7486,
         0.8434, 0.7859, 0.8006, 0.7762, 0.9161, 0.9102, 0.8754, 0.8900, 0.8903,
         0.7101, 0.7210, 0.8212, 0.8002, 0.7749, 0.8284, 0.7585, 0.8117, 0.7458,
         0.7942, 0.8259, 0.8315, 0.8267, 0.8092, 0.8949, 0.8666, 0.9146, 0.8007,
         0.8776, 0.8205, 0.8850, 0.7944, 0.7410, 0.8022, 0.7202, 0.8261, 0.7206,
         0.8087, 0.7488, 0.9439, 0.8753, 0.8024, 0.7947, 0.8331, 0.8633, 0.8933,
         0.8710, 0.8753, 0.7856, 0.8437, 0.8937, 0.8769, 0.8670, 0.8295, 0.7832,
         0.7729, 0.8595, 0.8228, 0.8323, 0.9276, 0.9092, 0.8107, 0.8392, 0.8235,
    

In [ ]:
# print({name: output.shape for name, output in features.items()})
# print(features['fc'][0])

In [4]:
print(a)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  